/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javatprecetas;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author ruddy
 */
public class ProyectoInterfazGrafica extends javax.swing.JFrame {

    /**
     * Creates new form ProyectoInterfazGrafica
     */
    public ProyectoInterfazGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonArchivoRecetas = new javax.swing.JButton();
        textFieldArchivoRecetas = new javax.swing.JTextField();
        scrollPaneArchivoRecetas = new javax.swing.JScrollPane();
        textAreaArchivoRecetas = new javax.swing.JTextArea();
        scrollPaneArchivoRecetas1 = new javax.swing.JScrollPane();
        textAreaArchivoIngredientes = new javax.swing.JTextArea();
        textFieldArchivoIngredientes = new javax.swing.JTextField();
        botonArchivoIngredientes = new javax.swing.JButton();
        botonProceso = new javax.swing.JButton();
        scrollPaneResultado = new javax.swing.JScrollPane();
        textAreaResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interfaz Grafica");
        setResizable(false);

        botonArchivoRecetas.setText("Elegir archivo recetas");
        botonArchivoRecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArchivoRecetasActionPerformed(evt);
            }
        });

        textFieldArchivoRecetas.setEditable(false);
        textFieldArchivoRecetas.setMinimumSize(new java.awt.Dimension(140, 22));
        textFieldArchivoRecetas.setPreferredSize(new java.awt.Dimension(140, 22));
        textFieldArchivoRecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldArchivoRecetasActionPerformed(evt);
            }
        });

        textAreaArchivoRecetas.setColumns(20);
        textAreaArchivoRecetas.setRows(5);
        scrollPaneArchivoRecetas.setViewportView(textAreaArchivoRecetas);

        textAreaArchivoIngredientes.setColumns(20);
        textAreaArchivoIngredientes.setRows(5);
        scrollPaneArchivoRecetas1.setViewportView(textAreaArchivoIngredientes);

        textFieldArchivoIngredientes.setEditable(false);
        textFieldArchivoIngredientes.setMinimumSize(new java.awt.Dimension(140, 22));
        textFieldArchivoIngredientes.setPreferredSize(new java.awt.Dimension(140, 22));
        textFieldArchivoIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldArchivoIngredientesActionPerformed(evt);
            }
        });

        botonArchivoIngredientes.setText("Elegir archivo ingredientes");
        botonArchivoIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArchivoIngredientesActionPerformed(evt);
            }
        });

        botonProceso.setText("Verificar");
        botonProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProcesoActionPerformed(evt);
            }
        });

        textAreaResultado.setColumns(20);
        textAreaResultado.setRows(5);
        scrollPaneResultado.setViewportView(textAreaResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollPaneArchivoRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(textFieldArchivoRecetas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonArchivoRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollPaneArchivoRecetas1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(textFieldArchivoIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonArchivoIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(botonProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(scrollPaneResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonArchivoIngredientes)
                        .addGap(33, 33, 33)
                        .addComponent(textFieldArchivoIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(scrollPaneArchivoRecetas1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonArchivoRecetas)
                        .addGap(33, 33, 33)
                        .addComponent(textFieldArchivoRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(scrollPaneArchivoRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(botonProceso)
                .addGap(18, 18, 18)
                .addComponent(scrollPaneResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonArchivoRecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArchivoRecetasActionPerformed
        // TODO add your handling code here:
        //System.out.println("apretar el boton");
        
        JFileChooser fileChooser = new JFileChooser(new File("."));
        
        int response = fileChooser.showOpenDialog(this);
        if(response == JFileChooser.APPROVE_OPTION){
            try {
                //System.out.println("abrimos el archivo");
                
                String ruta = fileChooser.getSelectedFile().getAbsolutePath();
                //System.out.println();
                textFieldArchivoRecetas.setText(ruta);
                
                File f = new File(ruta);
                Scanner sc = new Scanner(f);
                while(sc.hasNextLine()){
                    //System.out.println(sc.nextLine());
                    textAreaArchivoRecetas.append(sc.nextLine() + "\n");
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ProyectoInterfazGrafica.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
        
    }//GEN-LAST:event_botonArchivoRecetasActionPerformed

    private void textFieldArchivoRecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldArchivoRecetasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldArchivoRecetasActionPerformed

    private void textFieldArchivoIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldArchivoIngredientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldArchivoIngredientesActionPerformed

    private void botonArchivoIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArchivoIngredientesActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser(new File("."));
        
        int response = fileChooser.showOpenDialog(this);
        if(response == JFileChooser.APPROVE_OPTION){
            try {
                //System.out.println("abrimos el archivo");
                
                String ruta = fileChooser.getSelectedFile().getAbsolutePath();
                //System.out.println();
                textFieldArchivoIngredientes.setText(ruta);
                
                File f = new File(ruta);
                Scanner sc = new Scanner(f);
                while(sc.hasNextLine()){
                    //System.out.println(sc.nextLine());
                    textAreaArchivoIngredientes.append(sc.nextLine() + "\n");
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ProyectoInterfazGrafica.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
    }//GEN-LAST:event_botonArchivoIngredientesActionPerformed

    private void botonProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProcesoActionPerformed
        // TODO add your handling code here:
        //aca llamar al metodo para poder comparar los archivos
        String resultado = "Puedo hacer la receta"; //resultado del metodo
        textAreaResultado.setText("");
        textAreaResultado.append(resultado);
    }//GEN-LAST:event_botonProcesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProyectoInterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProyectoInterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProyectoInterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProyectoInterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProyectoInterfazGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonArchivoIngredientes;
    private javax.swing.JButton botonArchivoRecetas;
    private javax.swing.JButton botonProceso;
    private javax.swing.JScrollPane scrollPaneArchivoRecetas;
    private javax.swing.JScrollPane scrollPaneArchivoRecetas1;
    private javax.swing.JScrollPane scrollPaneResultado;
    private javax.swing.JTextArea textAreaArchivoIngredientes;
    private javax.swing.JTextArea textAreaArchivoRecetas;
    private javax.swing.JTextArea textAreaResultado;
    private javax.swing.JTextField textFieldArchivoIngredientes;
    private javax.swing.JTextField textFieldArchivoRecetas;
    // End of variables declaration//GEN-END:variables
}
